### ISSUE TITLE
mypy error 'has incompatible type "auto"'

### ISSUE THREAD

**Issue by kbakk** [irgeek/StrEnum#16]
Hi,

I'm getting an error message when running mypy. Here's a reproducer

`mypy.py`

```py
from enum import auto
from strenum import StrEnum

class HttpMethod(StrEnum):
    GET = auto()
    HEAD = auto()

class MyClass:
    def __init__(self, method: HttpMethod) -> None:
        self.method = method

MyClass(HttpMethod.GET)
```

mypy error message:

```
mypy --ignore-missing-imports mypy.py
mypy.py:16: error: Argument 1 to "MyClass" has incompatible type "auto"; expected "HttpMethod"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by irgeek** [comment]
This issue isn't specific to `sternum`--the `auto` that's imported from the `enum` package is a class, so I think `mypy` will always pick it up as being of type `auto`.

The only fix I can think of would be special-casing `auto` (in `mypy`) so it behaves more like `Any`.
