### ISSUE TITLE
When installing, StrEnum adds a `tests` package to site-packages

### ISSUE THREAD

**Issue by kbakk** [irgeek/StrEnum#17]
It seems that StrEnum installation creates a new package in `site-packages`.

```
ls <path-to-virtualenv>/site-packages/tests/
__init__.py  __pycache__  test_comparable.py  test_name_mangler.py  test_strenum_casefold.py  test_strenum_name_mangler.py  test_strenum.py
```

In my case, this caused tests in my project to fail, as importing something like `tests.mock_data` would no longer work.

I'm using Poetry, this may make matters worse in this case. 

I believe this is unintended.

**Comment by irgeek** [comment]
Thanks for the report. You're correct that this was unintended. I've released v0.4.8 to PyPI which should stop the `tests` dir from being installed.
