### ISSUE TITLE
Cleaner syntax suggestion

### ISSUE THREAD

**Issue by Elijas** [irgeek/StrEnum#3]
Some other libraries such as `@dataclass`, just use type hints without explicit value set
```@dataclass
class C:
    a: int
```

Maybe we could do the same and use this:
```
class HTTP(StrEnum):
    GET: str
    POST: str
```
instead of (or in addition to) the current syntax:
```
class HTTP(StrEnum):
    GET = auto()
    POST = auto()
```

I'd argue that makes it look more pythonic by being explicit in the intent of the variables being of type`str`

**Comment by irgeek** [comment]
Your proposed syntax doesn't actually create a class that acts like the enums in the standard library. It might be possible to make it work by adding a class decorator, but that decorator doesn't exist in the standard library and I have no intention of adding one to this library.

As for intent, subclassing `StrEnum` (which is a subclass of `str` and `enum.Enum`) already makes the intended type of class properties explicit. Adding `str` annotations would be redundant, and I'd argue, more confusing. The following snippet would not make any sense, but having an explicit type annotation for each member makes it seem like it might be possible:

```python
class HTTP(StrEnum):
    GET: str
    POST: int
```

The call to `auto`, on the other hand, is not redundant -- it's purpose it to explicitly state the at the _value_ for a particular enum member is intended to be the same as the _name_ of the member. In some cases that's not what you want, and `auto()` is not required to make `StrEnum` work:

```python
class HttpHeader(StrEnum):
    Host = auto()
    UserAgent = "User-Agent"
    Accept = auto()
    AcceptLanguage = "Accept-Language"
    AcceptEncoding = "Accept-Encoding"
    Referrer = "Referer"
    Connection = auto()
    UpgradeInsecureRequests = "Upgrade-Insecure-Requests"
    IfModifiedSince = "If-Modified-Since"
    IfNoneMatch = "If-Modified-Since"
    CacheControl = "Cache-Control"
```

**Comment by Elijas** [comment]
Thanks for a detailed reply! This makes sense :+1:
