### ISSUE TITLE
Make dumping StrEnum works 

### ISSUE THREAD

**Issue by TiansuYu** [irgeek/StrEnum#31]
Could you add this method to base `StrEnum` so that `pydantic.BaseModel.model_dump` and `list` when applied to `StrEnum` can return a normal string value? 
```
    class StrEnum:
    ...
    def __repr__(self) -> str:
        return str.__repr__(self.value)
```
I am currently subclassing `StrEnum` to make it work, but couldn't be bothered to add it to every class you have here. Do you think this is a reasonable design choice for this lib?

**Comment by TiansuYu** [comment]
PR https://github.com/irgeek/StrEnum/pull/33

**Comment by irgeek** [comment]
Could you explain to me why you feel this is a necessary change? This could be a breaking change for someone already using the library, so I'm hesitant to add it without understanding whether the improvement would outweigh the potential downsides. I feel like the current behaviour is quite useful in the REPL and other contexts.

**Comment by TiansuYu** [comment]
The motivation behind is to be able to use 
```
class Color(StrEnum)
    ...

list(Color)
assert "red" in list(Color)
```
Also the current state of the project is not compatible with pydantic. E.g. if I have defined a field with value `Color.RED`. Upon serialization, it will still print the normal rep of an Enum not its string value. `SomeModel.model_dump()`. I would have to call `Color.RED.value` in the field explicitly to make it work. 

Just some soft suggestions, feel free to ignore them if it irritates you. I can always patch it in mine and make it work.

**Comment by irgeek** [comment]
You example code already works, and the current behaviour matches the behaviour of the built-in IntEnum class:

```
In [1]: from strenum import StrEnum

In [2]: from enum import auto, IntEnum

In [3]: class Color(StrEnum):
   ...:     red = auto()
   ...:     green = auto()
   ...:     blue = auto()
   ...: 

In [4]: class Foo(IntEnum):
   ...:     foo = auto()
   ...:     bar = auto()
   ...:     baz = auto()
   ...: 

In [5]: colors, foos = list(Color), list(Foo)

In [6]: Color.red in colors
Out[6]: True

In [7]: "red" in colors
Out[7]: True

In [8]: Foo.foo in foos
Out[8]: True

In [9]: 1 in foos
Out[9]: True

In [10]: colors
Out[10]: [<Color.red: 'red'>, <Color.green: 'green'>, <Color.blue: 'blue'>]

In [11]: foos
Out[11]: [<Foo.foo: 1>, <Foo.bar: 2>, <Foo.baz: 3>]
```

Given that, I'm inclined to no make this change as I think it will be less surprising to users if the Enum-derived classes in this library match the behaviour of Enum-derived classes in the standard library.

Thank you for the contribution, though.
