### ISSUE TITLE
Support for __contains__

### ISSUE THREAD

**Issue by mscuthbert** [irgeek/StrEnum#5]
I found that StrEnums couldn't support "in" so I wrote this for my own work:

```
class StrEnumMeta(EnumMeta):
    def __contains__(cls, item):
        if isinstance(item, str):
            if item in cls.__members__.values():
                return True
            else:
                return False
        try:
            return super().__contains__(item)
        except TypeError:
            return False

class MyEnum(str, Enum, metaclass=StrEnumMeta):
    ITEM_ONE = 'one'
    ITEM_TWO = 'two'
```

Might be worth making a metaclass for this...

**Comment by irgeek** [comment]
Hi, thanks for the contribution.

`EnumMeta` is mentioned in the stdlib documentation, but it's API isn't actually documented. That make me very hesitant to add a dependency on it's current behaviour. Undocumented APIs have an annoyingly high possibility of changing.

Also, I haven't found a need to test membership of my StrEnum classes so far, and I'm having trouble imagining where I would use it. If you could explain to me when this is useful, I'd appreciate it.

**Comment by mscuthbert** [comment]
Sure thing -- I didn't know that `EnumMeta` wasn't fully documented.

I used to have a list of strings like (I'm working with music):

```
beamTypes = ['start', 'stop', 'partial']
```

but I'm replacing it with an enum:

```
class BeamType(StrEnum):
    START = 'start'
    STOP = 'stop'
    PARTIAL = 'partial'
```

but of course a lot of my users (music21 package) have gotten very used to passing in strings in previous versions:

```
myNote.beam.type = 'stop'
```

hence, why I'm moving gently using a StrEnum, so that this behavior can continue for a few more versions to give people time to adjust (with DeprecationNotices, etc.)  But I need to translate code such as:

```
if userBeamType not in beamTypes:  # raise ValueError or something like that.
```

but it would be great to be able to do this with the strings as well (just changing `beamTypes` to `BeamType`)

I'm changing over about 100 such magic-strings to StrEnum's throughout the code, so the easiest drop-in replacement is best for me.

The EnumMeta docs specifically state that `__contains__` is one of the things that it handles, so I think that this part of the API should remain somewhat stable.


> The EnumMeta metaclass is responsible for providing the `__contains__(), __dir__(), __iter__()` and other methods that allow one to do things with an Enum class that fail on a typical class, such as `list(Color)` or some_enum_var in Color. EnumMeta is responsible for ensuring that various other methods on the final Enum class are correct (such as `__new__(), __getnewargs__(), __str__()` and` __repr__()`).

Thanks again for the library!

**Comment by irgeek** [comment]
Thanks for the great response! I understand much better what you're trying to do now.

First, regarding the fact that `EnumMeta` provides `__contains__()`, the documentation is referring to the existing implementation that checks whether the argument is a member of the enum -- not something that can be converted to a member of the enum. Like this:

```pycon
>>> from strenum import StrEnum
>>> class BeamType(StrEnum):
    START = 'start'
    STOP = 'stop'
    PARTIAL = 'partial'
>>> BeamType.START in BeamType
True
>>> "start" in BeamType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 321, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumMeta'
```

As that documentation states, `EnumMeta` also provides `__iter__()`, so you could try this:

```pycon
>>> "start" in iter(BeamType)
True
```

Using `iter()` works, but it might preform poorly if you're checking often as it will be doing a linear search on every check. Instead, you could create a `set()` of all the members and us that in your test:

```pycon
>>> _beam_type_members = set(BeamType)
>>> _beam_type_members
{<BeamType.START: 'start'>, <BeamType.STOP: 'stop'>, <BeamType.PARTIAL: 'partial'>}
>>> "start" in _beam_type_members
True
>>> BeamType.START in _beam_type_members
True
```

Here's one final idea for you:

```python
import warnings

def ensure_enum(enum, value):
    # This will throw a ValueError if the passed in value isn't a value that
    # can be converted to a member of the enum:
    enum_member = enum(value)

    if enum_member is value:
        return enum_member

    # If we get here, the passed value was valid, but it wasn't an enum member
    # so we throw a deprecation warning:
    warnings.warn(
        f"Passing a raw value is deprecated. Pass a member of {enum.__name__} instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    return enum_member
```

I your code, then, you'd just need to do the following wherever you receive a value you expect to be an enum member:

```python
userBeamType = ensure_enum(BeamType, userBeamType)
```

The `ensure_enum` function will take care of warning the user that they should be using the enums.

Will any of these solutions work for you? I think the last one, especially, is a bit more clear about what's going on -- and as we all remember from _The Zen of Python_:

> Explicit is better than implicit.

I also think it'd be dangerous in the long term to change the implementation of `__contains__()` for enums. Serialisation libraries, for instance, could very reasonably rely on the standard library behaviour and changing it for `StrEnum` would then be incompatible with libraries like that.

**Comment by irgeek** [comment]
I added a couple of new subclasses you might find useful.

Instead of this:

```python
from strenum import StrEnum

class OldBeamType(StrEnum):
    START = 'start'
    STOP = 'stop'
    PARTIAL = 'partial'
```

You can now do this:

```python
from enum import auto
from strenum import LowercaseStrEnum

class BeamType(LowercaseStrEnum):
    START = auto()
    STOP = auto()
    PARTIAL = auto()
```

There's also an UppercaseStrEnum class that folds the names to upper case.

I just pushed version 0.4.3 to PyPi with these changes.

**Comment by mscuthbert** [comment]
> Thanks for the great response! I understand much better what you're trying to do now.
> 
> First, regarding the fact that `EnumMeta` provides `__contains__()`, the documentation is referring to the existing implementation that checks whether the argument is a member of the enum -- not something that can be converted to a member of the enum. 

Ah, you're absolutely right, I had thought that this worked with IntEnums and therefore a StrEnum should have this capability also, but I was mistaken:

```
from enum import IntEnum

class FourFive(IntEnum):
    FOUR = 4
    FIVE = 5

4 in FourFive
```

This does in fact raise a TypeError.  So since the point of making this library is to have a parallel to IntEnum for strings, it shouldn't be in there.  But maybe someone will still find this discussion useful for their own work (I'm keeping it in my own implementation, for instance).

Thanks for the great ideas!
