### ISSUE TITLE
Case-insensitive StrEnum

### ISSUE THREAD

**Issue by espdev** [irgeek/StrEnum#9]
Is there any way to make case-insensitive `StrEnum` without changing `EnumMeta` class?

That is what I mean:
```python
class InterpMethods(StrEnum, case_sensitive=False):
    LINEAR = auto()
    CUBIC = auto()
    LANCZOS = auto()

print(InterpMethods.LINEAR)
# <InterpMethods.LINEAR: 'LINEAR'>

assert InterpMethods.LINEAR == 'linear'
assert InterpMethods.LINEAR == 'Linear'
assert InterpMethods.LINEAR == 'LINEAR'

assert InterpMethods('linear') == InterpMethods.LINEAR
assert InterpMethods('Linear') == InterpMethods.LINEAR
assert InterpMethods('LINEAR') == InterpMethods.LINEAR
```

Real-life usage example:
```python
import click
from strenum import StrEnum, auto
from something import linear, cubic, lanczos

class InterpMethods(StrEnum, case_sensitive=False):
    LINEAR = auto(), linear
    CUBIC = auto(), cubic
    LANCZOS = auto(), lanczos
    
    def __new__(cls, value, calculator):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.apply = calculator
        return obj

@click.command()
@click.option('-m', '--method', type=click.Choices(InterpMethods, case_sensitive=False))
def cli(method: InterpMethods):
    ...
    result = method.apply(data)

# Usage of CLI:
# > cli -m linear
# > cli -m Linear
# > cli -m LINEAR
```

**Comment by irgeek** [comment]
The syntax example you've provided isn't actually valid in Python -- class definitions cannot have keyword arguments like that. You can accomplish case-insensitive matching, though, with a mix-in class that implements the Python “rich comparison” methods.

This does seem like a useful feature. As such, I've just added a [strenum.mixins.Comparable](https://github.com/irgeek/StrEnum/blob/ed1b7910b792f3842f1d742958a2455c7cb0a72b/strenum/mixins.py) class that you can mix with the other `strenum` classes to customise them -- all you need to do is implement a function that return the two alternative values that should be compared. Something like the following this should do what you want:


```python
from enum import auto
from strenum import StrEnum
from strenum.mixins import Comparable


class InterpMethods(Comparable, StrEnum):
    LINEAR = auto()
    CUBIC = auto()
    LANCZOS = auto()

    # This method is what provide the case-insensitive magic. It's gets passed
    # the Enum member being compared along with the other value. It needs to
    # return two values to compare. Make sure you don't return the Enum member
    # itself -- the resulting comparison would call _cmp_values again and you
    # end up with infinite recursion.
    def _cmp_values(self, other):
        return self.value, str(other).upper()


assert InterpMethods.LINEAR == "LINEAR"
assert InterpMethods.LINEAR == "linear"
assert InterpMethods.LINEAR == "Linear"
```

I've added documentation for this [here](https://strenum.readthedocs.io/en/latest/api_ref.html#module-strenum.mixins)

**Comment by espdev** [comment]
> class definitions cannot have keyword arguments like that

This is valid syntax. See the documentation here: https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__

Thank you for `strenum.mixins.Comparable`! This is a good solution. I will try it soon.

**Comment by espdev** [comment]
Link to PR: #10

**Comment by irgeek** [comment]
> This is a valid syntax.

I guess it’s true you learn something new every day — I haven’t seen `__init_subclass__` before. Very interesting.

I hope Comparable works for your needs.
